name: Android Release Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.2.1"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Build release APK
        run: gradle assembleRelease --stacktrace

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: Auto-Clear-Notification-release-apk
          path: app/build/outputs/apk/release/*.apk
